id = "etcd"
name = "ETCD"
icon = "https://i.imgur.com/jyDr9hI.png"
description = "etcd is a distributed key-value store designed to securely store data across a cluster."

[source]
image = "bitnami/etcd:3.5.10"

[[ports]]
id = "client"
port = 2379
type = "TCP"

[[ports]]
id = "peer"
port = 2380
type = "TCP"

[[volumes]]
id = "data"
dir = "/var/lib/etcd"

[env]
ALLOW_NONE_AUTHENTICATION = { default = "yes" }
