id = "milvus"
name = "Milvus"
icon = "https://avatars.githubusercontent.com/u/51735404?s=200&v=4"
description = "Vector database built for scalable similarity search"

[source]
image = "milvusdb/milvus:v2.3.2"

[[ports]]
id = "database"
port = 19530
type = "TCP"

[[ports]]
id = "database"
port = 9091
type = "TCP"

[[volumes]]
id = "data"
dir = "/var/lib/milvus"

[env]
ETCD_ENDPOINTS =  { default = "etcd:2379", expose = true }
MINIO_ADDRESS =  { default = "minio:9000", expose = true }

MILVUS_HOST = { default = "${CONTAINER_HOSTNAME}", expose = true, readonly = true }
MILVUS_USERNAME = { default = "root", expose = true, readonly = true }
MILVUS_PASSWORD = { default = "Milvus", expose = true, readonly = true }
